//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_Post
    {
        public int Eng_PostId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Rec_Date { get; set; }
        public string Status { get; set; }
        public string Agnt_Conf { get; set; }
        public string Poster_Conf { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Post Post { get; set; }
    }
}
