//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DtransEntities : DbContext
    {
        public DtransEntities()
            : base("name=DtransEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Agent_Post> Agent_Post { get; set; }
        public virtual DbSet<ChatRoom> ChatRooms { get; set; }
        public virtual DbSet<HiddenChat> HiddenChats { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<ProfileType> ProfileTypes { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Shop_Centres> Shop_Centres { get; set; }
        public virtual DbSet<Shop_Subscription> Shop_Subscription { get; set; }
        public virtual DbSet<ShopItem> ShopItems { get; set; }
        public virtual DbSet<ShopLogin> ShopLogins { get; set; }
        public virtual DbSet<ShopTransaction> ShopTransactions { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<TagPay> TagPays { get; set; }
        public virtual DbSet<TransactionFee> TransactionFees { get; set; }
        public virtual DbSet<PostsByAgent> PostsByAgents { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<payment_requests> payment_requests { get; set; }
    }
}
