//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiddenChat
    {
        public int HiddenId { get; set; }
        public Nullable<int> SubsciberId { get; set; }
        public Nullable<int> ChatId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
