//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> Recipient { get; set; }
        public string Message { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual Notification Notifications1 { get; set; }
        public virtual Notification Notification1 { get; set; }
    }
}
