//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_requests
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_requested { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
        public Nullable<int> agent_id { get; set; }
        public string is_accepted { get; set; }
        public string is_paid { get; set; }
        public string authorised_by { get; set; }
        public Nullable<System.DateTime> date_authorised { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
