//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsByAgent
    {
        public int Id { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string DatePosted { get; set; }
        public string PickUp { get; set; }
        public string LocationFrom { get; set; }
        public string LocationTo { get; set; }
        public string DepatureDate { get; set; }
        public string TransPort { get; set; }
        public string ETA { get; set; }
        public string Fragility { get; set; }
        public string Weight { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
