//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.TimeSpan> Time_Created { get; set; }
        public string Reff_Number { get; set; }
        public string Pay_Method { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SubscriberID { get; set; }
        public string Sub_Phone { get; set; }
        public string Status { get; set; }
        public string PollUrl { get; set; }
        public Nullable<double> TransactionFee { get; set; }
    
        public virtual ShopItem ShopItem { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
