//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Centres
    {
        public int CentreId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string Contact_Phone { get; set; }
        public string Account_Number { get; set; }
        public string Contact_Email { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
