//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Subscription
    {
        public int SubscriptionID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Status { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
