//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Shop_Centres = new HashSet<Shop_Centres>();
            this.Shop_Subscription = new HashSet<Shop_Subscription>();
            this.ShopItems = new HashSet<ShopItem>();
            this.ShopLogins = new HashSet<ShopLogin>();
        }
    
        public int ShopID { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_Address { get; set; }
        public string Contact_Number { get; set; }
        public string Contact_Person { get; set; }
        public string Logo { get; set; }
        public string Cover_Image { get; set; }
        public string Shop_Motto { get; set; }
        public string Shop_Email { get; set; }
        public Nullable<int> Profile_Type { get; set; }
    
        public virtual ProfileType ProfileType { get; set; }
        public virtual ICollection<Shop_Centres> Shop_Centres { get; set; }
        public virtual ICollection<Shop_Subscription> Shop_Subscription { get; set; }
        public virtual ICollection<ShopItem> ShopItems { get; set; }
        public virtual ICollection<ShopLogin> ShopLogins { get; set; }
    }
}
