//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public ShopItem()
        {
            this.ShopTransactions = new HashSet<ShopTransaction>();
        }
    
        public int ItemID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Bar_Code { get; set; }
        public string Unique_ID { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ICollection<ShopTransaction> ShopTransactions { get; set; }
    }
}
