//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public Subscriber()
        {
            this.Agents = new HashSet<Agent>();
            this.ChatRooms = new HashSet<ChatRoom>();
            this.HiddenChats = new HashSet<HiddenChat>();
            this.Notifications = new HashSet<Notification>();
            this.Posts = new HashSet<Post>();
            this.ShopTransactions = new HashSet<ShopTransaction>();
            this.TagPays = new HashSet<TagPay>();
        }
    
        public int SubscriberId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string RepeatPassword { get; set; }
        public string VerificationCode { get; set; }
        public string ProfilePic { get; set; }
        public string Status { get; set; }
        public string IDNumber { get; set; }
        public string Address { get; set; }
        public string DateRegistered { get; set; }
        public ImageUp upload { get; set; }
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<ChatRoom> ChatRooms { get; set; }
        public virtual ICollection<HiddenChat> HiddenChats { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<ShopTransaction> ShopTransactions { get; set; }
        public virtual ICollection<TagPay> TagPays { get; set; }
    }
}
