//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagPay
    {
        public int Id { get; set; }
        public string AgentId { get; set; }
        public string MerchantId { get; set; }
        public string Client { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
        public string ReferenceId { get; set; }
        public string Result { get; set; }
        public string TransactionId { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> SubscriberId { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
