//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionFee
    {
        public int transID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> postID { get; set; }
        public Nullable<double> amount { get; set; }
        public string reff_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Status { get; set; }
        public string PollURL { get; set; }
        public string paymentReff { get; set; }
        public string Hash { get; set; }
        public string Submitted { get; set; }
    }
}
