//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTransAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int ID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string Total { get; set; }
        public string Available { get; set; }
        public string Pending { get; set; }
        public string Drawable { get; set; }
        public string Overal { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
